Restructure branching logic

diff --git a/gem-changelog-update-check/action.yml b/gem-changelog-update-check/action.yml
--- a/gem-changelog-update-check/action.yml
+++ b/gem-changelog-update-check/action.yml
@@ -20,21 +20,17 @@ runs:
         changelog_file="${{ inputs.changelog-file-path }}"
         echo "Changes relative to main branch:"
         echo "$changes"
+
         if [ ! -f "$changelog_file" ]
         then
           echo "No $changelog_file to update"
           exit 0
-        fi
-        if echo "$changes" | grep -Eq "$file_regex"
+        elif echo "$changes" | grep -Fqx "$changelog_file"
         then
-          echo "Changes requiring an update of $changelog_file are present"
-          if echo "$changes" | grep -Fqx "$changelog_file"
-          then
-            echo "$changelog_file updated"
-            exit 0
-          else
-            echo "$changelog_file has not been updated" >&2
-            exit 1
-          fi
+          exit 0
+        elif echo "$changes" | grep -Eq "$file_regex"
+        then
+          echo "changes to $changelog_file required" >&2
+          exit 1
         fi
       shell: bash
